#!/usr/bin/env bash
username="$1"
git clone https://github.com/rudy-in/endeavouros-hyprland.git
cd endeavouros-hyprland
cp -R .config /home/$username/
chmod +x /home/$username/.config/hypr/scripts
chmod +x /home/$username/.config/hypr/scripts/*.sh
ln -s /home/$username/.config/waybar/conf/w1-config-desktop.jsonc /home/$username/.config/waybar/config.jsonc
ln -s /home/$username/.config/waybar/style/w1-style.css /home/$username/.config/waybar/style.css
ln -s /home/$username/.config/waybar/conf/w2-config-laptop.jsonc /home/$username/.config/waybar/config.jsonc
ln -s /home/$username/.config/waybar/style/w2-style.css /home/$username/.config/waybar/style.css
cp -R .local /home/$username/
cp -R .icons /home/$username/
cd ..
rm -rf endeavouros-hyprland
chown -R $username:$username /home/$username
wget https://raw.githubusercontent.com/rudy-in/endeavouros-hyprland/main/hypr_packages.list
pacman -S --needed --noconfirm - < hypr_packages.list
rm hypr_packages.list
cd /
