#!/usr/bin/env bash
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
username="$1"
git clone https://github.com/killajoe/endeavouros-hyprland.git
cd endeavouros-hyprland
cp -R .config /home/$username/
chmod -R +x /home/$username/.config/hypr/scripts
cp -R .local /home/$username/
cp -R .icons /home/$username/
cd ..
rm -rf endeavouros-hyprland
chown -R $username:$username /home/$username
su $username
cd /home/$username
wget https://raw.githubusercontent.com/killajoe/endeavouros-hyprland/main/hypr_packages.list
sudo pacman -S --needed --noconfirm - < /home/$username/hypr_packages.list
rm /home/$username/hypr_packages.list
cd /
