#!/usr/bin/env bash
username="$1"
git clone https://github.com/rudy-in/endeavouros-hyprland.git
cd endeavouros-hyprland
cp -R .config /home/$username/
chmod -R +x /home/$username/.config/hypr/scripts
cp -R .local /home/$username/
cp -R .icons /home/$username/
cd ..
rm -rf endeavouros-hyprland
chown -R $username:$username /home/$username
wget https://raw.githubusercontent.com/rudy-in/endeavouros-hyprland/main/hypr_packages.list
pacman -S --needed --noconfirm - < hypr_packages.list
rm hypr_packages.list
cd /
