#!/bin/bash

CONFIG="$HOME/.config/waybar/menu/config"
STYLE="$HOME/.config/waybar/menu/style.css"


if [[ ! $(pidof wofi) ]]; then
  wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
  pkill wofi
fi

# waybar gets toggled when esc is pressed
# Terminate already running bar instances

killall -q waybar

# Wait until the waybar processes have been shut down

while pgrep -x waybar >/dev/null; do sleep 1; done

# Launch main

waybar
