#!/bin/bash

CONFIG="$HOME/.config/waybar/menu/config"
STYLE="$HOME/.config/waybar/menu/style.css"


if [[ ! $(pidof wofi) ]]; then
  wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
  pkill wofi
fi


